apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    apps: jupyterhub
    version: v1
    env: dev
spec:
  selector:
    matchLabels:
      apps: jupyterhub
      version: v1
      env: dev
  template:
    metadata:
      name: jupyterhub
      labels:
        apps: jupyterhub
        version: v1
        env: dev
    spec:
      containers:
        - name: jupyterhub-container
          image: tusharthapliyal/jupyterhub:v1
          ports:
            - containerPort: 8888
              name: jupyterhub-port
          volumeMounts:
            - name: local-volume
              mountPath: /home/  
      volumes:
      - name: local-volume
        hostPath:
          path: /home/              # The path on the host machine
          type: DirectoryOrCreate         # Creates the directory if it doesn't exist
