apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-nodeport
  labels:
    apps: jupyterhub
    version: v1
    env: dev
spec:
  type: NodePort
  selector:
    apps: jupyterhub
    version: v1
    env: dev
  ports:
    - protocol: TCP
      port: 80        # Port that the service will expose
      targetPort: jupyterhub-port # Port on the container to which the traffic will be forwarded
      nodePort: 30000  # Port on the node where the service will be accessible
