apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    apps: jupyterhub
    version: v2
    env: dev
spec:
  selector:
    matchLabels:
      apps: jupyterhub
      version: v2
      env: dev
  template:
    metadata:
      name: jupyterhub
      labels:
        apps: jupyterhub
        version: v2
        env: dev
    spec:
      containers:
        - name: jupyterhub-container
          image: tusharthapliyal/jupyterhub:v2
          ports:
            - containerPort: 8000
              name: jupyterhub-port
          volumeMounts:
            - name: local-volume
              mountPath: /home 
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: my-pvc  # Reference the PVC

